execute if score @s techsword.attack_cooldown matches ..0 run title @s actionbar {"text": "|||||||||||||||||||||||||", "color": "green"}

execute if score @s techsword.attack_cooldown matches 1 run title @s actionbar [{"text": "|", "color": "red"},{"text": "||||||||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 2 run title @s actionbar [{"text": "||", "color": "red"},{"text": "|||||||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 3 run title @s actionbar [{"text": "|||", "color": "red"},{"text": "||||||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 4 run title @s actionbar [{"text": "||||", "color": "red"},{"text": "|||||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 5 run title @s actionbar [{"text": "|||||", "color": "red"},{"text": "||||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 6 run title @s actionbar [{"text": "||||||", "color": "red"},{"text": "|||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 7 run title @s actionbar [{"text": "|||||||", "color": "red"},{"text": "||||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 8 run title @s actionbar [{"text": "||||||||", "color": "red"},{"text": "|||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 9 run title @s actionbar [{"text": "|||||||||", "color": "red"},{"text": "||||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 10 run title @s actionbar [{"text": "||||||||||", "color": "red"},{"text": "|||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 11 run title @s actionbar [{"text": "|||||||||||", "color": "red"},{"text": "||||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 12 run title @s actionbar [{"text": "||||||||||||", "color": "red"},{"text": "|||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 13 run title @s actionbar [{"text": "|||||||||||||", "color": "red"},{"text": "||||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 14 run title @s actionbar [{"text": "||||||||||||||", "color": "red"},{"text": "|||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 15 run title @s actionbar [{"text": "|||||||||||||||", "color": "red"},{"text": "||||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 16 run title @s actionbar [{"text": "||||||||||||||||", "color": "red"},{"text": "|||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 17 run title @s actionbar [{"text": "|||||||||||||||||", "color": "red"},{"text": "||||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 18 run title @s actionbar [{"text": "||||||||||||||||||", "color": "red"},{"text": "|||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 19 run title @s actionbar [{"text": "|||||||||||||||||||", "color": "red"},{"text": "||||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 20 run title @s actionbar [{"text": "||||||||||||||||||||", "color": "red"},{"text": "|||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 21 run title @s actionbar [{"text": "|||||||||||||||||||||", "color": "red"},{"text": "||||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 22 run title @s actionbar [{"text": "||||||||||||||||||||||", "color": "red"},{"text": "|||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 23 run title @s actionbar [{"text": "|||||||||||||||||||||||", "color": "red"},{"text": "||", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 24 run title @s actionbar [{"text": "||||||||||||||||||||||||", "color": "red"},{"text": "|", "color": "green"}]
execute if score @s techsword.attack_cooldown matches 25 run title @s actionbar [{"text": "|||||||||||||||||||||||||", "color": "red"},{"text": "", "color": "green"}]